In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
df = pandas.read_csv("/content/drive/MyDrive/0.MKCE/Datasets/restaurants.csv")

In [ ]:
X = df['Food_Quality']

Y = df['Price']

In [ ]:
X = sm.add_constant(X)

model = sm.OLS(Y, X).fit()

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/tsatools.py:117: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


In [ ]:
summary = model.summary()
print(summary)

                            OLS Regression Results                            
Dep. Variable:                  Price   R-squared:                       0.321
Model:                            OLS   Adj. R-squared:                  0.300
Method:                 Least Squares   F-statistic:                     15.15
Date:                Thu, 05 May 2022   Prob (F-statistic):           0.000474
Time:                        08:08:31   Log-Likelihood:                -111.50
No. Observations:                  34   AIC:                             227.0
Df Residuals:                      32   BIC:                             230.0
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const          -23.9019     17.718     -1.349   

In [ ]:
sm.stats.linear_rainbow(model)

(3.95352909410105, 0.0051865838644822495)

In [ ]:
model.params

const          -23.901869
Food_Quality     3.249533
dtype: float64

In [ ]:
model.rsquared

0.3212711726017563

In [ ]:
df

Restaurant_ID  Food_Quality  Service_Quality  Price
0            ADS            22               20     43
1            BLG            20               19     32
2            CMK            21               18     34
3            KLS            20               17     41
4            IOS            24               21     54
5            UWO            22               21     52
6            USL            22               21     34
7            UKS            20               21     34
8            PLE            22               22     39
9            HEL            21               19     44
10           HQP            19               20     45
11           QUS            21               21     47
12           PLE            21               20     52
13           YWL            19               19     35
14           GQL            20               21     47
15           PEL            21               21     37
16           TLS            22               23     45
17           NSL            24               22     57
18           NBS            19               18     38
19           ORL            22               22     51
20           PLE            23               23     54
21           QIO            23               21     51
22           LEP            20               18     38
23           TLD            22               21     49
24           FPL            22               22     45
25           UID            19               19     37
26           PLQ            22               22     50
27           ALP            20               18     43
28           SLR            22               20     49
29           ULA            21               20     65
30           UEP            20               18     34
31           MLA            21               18     51
32           LMD            20               19     49
33           UWL            23               23     51

In [ ]:
df.shape

(34, 4)

In [ ]:
x=sm.add_constant(X)
model=sm.OLS(Y,X).fit()

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/tsatools.py:117: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


In [ ]:
df=df.drop(columns=["Restaurant_ID"],axis= 1)

In [ ]:
df

Food_Quality  Service_Quality  Price
0             22               20     43
1             20               19     32
2             21               18     34
3             20               17     41
4             24               21     54
5             22               21     52
6             22               21     34
7             20               21     34
8             22               22     39
9             21               19     44
10            19               20     45
11            21               21     47
12            21               20     52
13            19               19     35
14            20               21     47
15            21               21     37
16            22               23     45
17            24               22     57
18            19               18     38
19            22               22     51
20            23               23     54
21            23               21     51
22            20               18     38
23            22               21     49
24            22               22     45
25            19               19     37
26            22               22     50
27            20               18     43
28            22               20     49
29            21               20     65
30            20               18     34
31            21               18     51
32            20               19     49
33            23               23     51

In [ ]:
x=df.drop(['Price'],axis=1)
y=df['Price']

In [ ]:
type(x)

pandas.core.frame.DataFrame

In [ ]:
type(y)

pandas.core.series.Series

In [ ]:
x=x.values
y=y.values

In [ ]:
type(x)

numpy.ndarray

In [ ]:
type(y)

numpy.ndarray

In [ ]:
#splittingthe dataset into the traning set and test set
from sklearn.model_selection import train_test_split
x_training_set,x_testing_set,y_training_set,y_testing_set=train_test_split(x,y,test_size=0.2,random_state=0)


In [ ]:
x_training_set

array([[22, 23],
       [19, 20],
       [23, 23],
       [20, 18],
       [22, 22],
       [21, 21],
       [22, 22],
       [19, 19],
       [22, 20],
       [22, 21],
       [20, 21],
       [21, 20],
       [20, 18],
       [20, 19],
       [21, 20],
       [22, 21],
       [22, 21],
       [24, 21],
       [19, 18],
       [23, 21],
       [22, 22],
       [21, 19],
       [20, 21],
       [20, 19],
       [20, 18],
       [20, 17],
       [22, 20]])

In [ ]:
x_testing_set

array([[21, 21],
       [23, 23],
       [19, 19],
       [24, 22],
       [21, 18],
       [22, 22],
       [21, 18]])

In [ ]:
y_training_set

array([45, 45, 51, 34, 45, 37, 39, 35, 49, 52, 47, 65, 38, 32, 52, 34, 49,
       54, 38, 51, 51, 44, 34, 49, 43, 41, 43])

In [ ]:
y_testing_set

array([47, 54, 37, 57, 34, 50, 51])

In [ ]:
#Fitting multiple linear regression to the traning set
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_training_set,y_training_set)

LinearRegression()

In [ ]:
#the coefficient
print('cofficients: \n',regressor.coef_)

cofficients: 
 [ 2.88046272 -0.04627249]


In [ ]:
regressor.intercept_

-15.435732647814902

In [ ]:
#prediciting the test set results
y_pred=regressor.predict(x_testing_set)
y_pred

array([44.08226221, 49.75064267, 38.41388175, 52.67737789, 44.22107969,
       46.91645244, 44.22107969])

In [ ]:
#the mean squared error


print("Mean squared error:",sklearn.metrics.mean_squared_error(y_testing_set,y_pred))

NameError: ignored

In [ ]:
#explained variance score: 1 is perfect predicition 
print("varance score:",sklearn.metrics.r2_score(y_testing_set,y_pred))

NameError: ignored

In [ ]:
#compare actual data with predicted data
import pandas as pd
y_test=pd.DataFrame(y_testing_set)
y_prediction =pd.DataFrame(y_pred)
comparsion =pd.concat([y_test,y_predicition],aix=1)

NameError: ignored

In [ ]:
comparison.to_csv('regression comparison.csv')